# modules configuration file

# Common twitter keys
twitter:
  consumerKey:
  consumerSecret:
   
#sharedConsumerKey:
#sharedConsumerSecret:
#sharedAccessToken:
#sharedAccessTokenSecret:

---

# twitterstream source module properties
#source:
#  twitterstream:
#    consumerKey: ${sharedConsumerKey:}
#    consumerSecret: ${sharedConsumerSecret:}
#    accessToken: ${sharedAccessToken:}
#    accessTokenSecret: ${sharedAccessTokenSecret:}

---

# twittersearch source module properties
#source:
#  twittersearch:
#    consumerKey: ${sharedConsumerKey:}
#    consumerSecret: ${sharedConsumerSecret:}

---

# RabbitMQ shared module properties
#sharedRabbitHost: localhost
#sharedRabbitPort: 5672
#sharedRabbitUsername: guest
#sharedRabbitPassword: guest
#sharedRabbitVhost: /

---
