# XD Configuration file
# You can set properties here to override the default which
# are set in the application.yml file loaded by Spring Boot.
#
# Propertes set in here will take precedence.
#
# Alternatively, you can set the environment variable XD_CONFIG
# to point to a file (use a file:// URL). That file will then be
# used instead.

#XD data transport (default is redis for distributed, local for single node)
#xd:
#  transport: rabbit

#Disable batch database initialization
#spring:
#  batch:
#    initializer:
#       enabled: false

---
#Config for singlenode embedded hsql
#spring:
#  profiles: singlenode
#singlenode:
#  embeddedHsql: true

---
#Config for use with HSQLDB
#
#Change the database host, port and name
#hsql:
#  server:
#    host: localhost
#    port: 9102
#    dbname: xdjob
#Change database username and password
#spring:
#  datasource:
#    url: jdbc:hsqldb:hsql://${hsql.server.host:localhost}:${hsql.server.port:9101}/${hsql.server.dbname:xdjob}
#    username: sa
#    password:
#    driverClassName: org.hsqldb.jdbc.JDBCDriver

#Config for use with MySQL - uncomment and edit with relevant values for your environment
#spring:
#  datasource:
#    url: jdbc:mysql://yourDBhost:3306/yourDB
#    username: yourUsername
#    password: yourPassword
#    driverClassName: com.mysql.jdbc.Driver


#Config for use with Postgres - uncomment and edit with relevant values for your environment
#spring:
#  datasource:
#    url: jdbc:postgresql://yourDBhost:5432/yourDB
#    username: yourUsername
#    password: yourPassword
#    driverClassName: org.postgresql.Driver

---
# Config to enable/disable JMX/jolokia endpoints
#XD_JMX_ENABLED: true
#endpoints:
#  jolokia:
#    enabled: ${XD_JMX_ENABLED:true}
#  jmx:
#    enabled: ${XD_JMX_ENABLED:true}
#    uniqueNames: true

---
# Redis properties
#spring:
#  redis:
#   port: 6379
#   host: localhost

#Port that admin-ui is listening on
#server:
#  port: 9393

---
# RabbitMQ properties
#spring:
#  rabbitmq:
#   host: localhost
#   port: 5672
#   username: guest
#   password: guest
#   virtual_host: /

---
# Hadoop properties
#spring:
#  hadoop:
#   fsUri: hdfs://localhost:8020

---
#Zookeeper properties
# client connect string: host1:port1,host2:port2,...,hostN:portN
#zk:
#  client:
#     connect: localhost:2181
---
#Container Attributes: Used to target containers configured with attribute values for module deployment by specifying attribute expressions in the deployment manifest.
#'groups' is a native XD convention for targeting a group of container instances and is also supported as a command line option and environment variable XD_CONTAINER_GROUPS.
# A container instance may belong to multiple groups. XD Also supports any user defined attributes provided here.
#
#xd:
#  container:
#    groups:  group1,group2
#    color: green
#    foo: bar
---
# User Extensions: Where XD scans the classpath to discover extended container configuration to add beans to the Plugins context.
# Each property may be a comma delimited string. 'basepackages' refers to package names used for
# annotated component (@Configuration or @Component stereotypes) scanning. 'locations' is a list of root resource directories containing XML or Groovy configuration. 
# XD prepends classpath:* if no prefix included and appends **/*.* to each location
#xd:
#  extensions:
#      basepackages: com.acme.xd.extensions
#      locations: META-INF/spring-xd/ext
---
