spring:
  profiles:
    active: default,hsqldb
  datasource:
    url: jdbc:hsqldb:hsql://${hsql.server.host:localhost}:${hsql.server.port:9101}/${hsql.server.dbname:xdjob}
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver

XD_ANALYTICS: ${analytics:redis}
XD_TRANSPORT: ${transport:redis}
XD_STORE: ${store:redis}
XD_HOME: ${xdHomeDir:file:..}

server:
  port: ${PORT:9393}

---

spring:
  profiles: memory
transport: local
analytics: memory
store: memory
server:
  port: 0
management:
  port: 0

---

spring:
  profiles: rabbit
transport: rabbit

---

spring:
  profiles: cloud

xdHomeDir: file:.

---

spring:
  profiles: adminServer

---

spring:
  profiles: node
  batch:
    initializer:
      enabled: false
management:
  port: ${PORT:9292}
server:
  port: ${PORT:9292}

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: single
transport: local
store: memory
analytics: memory

