XD_ANALYTICS: ${analytics:redis}
XD_TRANSPORT: ${transport:redis}
XD_STORE: ${store:redis}
XD_HOME: ${xdHomeDir:..}

---

spring:
  profiles: adminServer
  
---

spring:
  profiles: node
management:
  port: 9000
  
---
spring:
  profiles: singleNode
transport: local
store: memory
analytics: memory
management:
  port: 0
