XD_ANALYTICS: ${analytics:redis}
XD_TRANSPORT: ${transport:redis}
XD_STORE: ${store:redis}
XD_HOME: ${xdHomeDir:..}

---

spring:
  profiles: cloud
  database:
    url: ${spring.datasource.url}
    driverClassName: ${spring.datasource.driverClassName}
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
redis:
  hostname: ${vcap.services.redis.credentials.hostname:localhost}
  port: ${vcap.services.redis.credentials.port:6379}
  password: ${vcap.services.redis.credentials.password:#{null}}

xdHomeDir: '.'

---

spring:
  profiles: adminServer
  
---

spring:
  profiles: node
management:
  port: 9000
  
---
spring:
  profiles: singleNode
transport: local
store: memory
analytics: memory
management:
  port: 0
