XD_ANALYTICS: ${analytics:redis}
XD_TRANSPORT: ${transport:redis}
XD_STORE: ${store:redis}
XD_HOME: ${xdHomeDir:..}
server:
  port: ${PORT:8080}

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost/test
    username: root
    password: changeme
    driverClassName: org.postgresql.Driver

---

spring:
  profiles: cloud
redis:
  hostname: ${vcap.services.redis.credentials.hostname:localhost}
  port: ${vcap.services.redis.credentials.port:6379}
  password: ${vcap.services.redis.credentials.password:#{null}}

XD_HOME: .

---

spring:
  profiles: adminServer
  
---

spring:
  profiles: node
management:
  port: ${PORT:9000}
server:
  port: ${PORT:9000}
  
---
spring:
  profiles: singleNode
transport: local
store: memory
analytics: memory
management:
  port: 0
