spring:
  profiles:
    active: default,hsqldb
  datasource:
    url: jdbc:hsqldb:hsql://${hsql.server.host:localhost}:${hsql.server.port:9101}/${hsql.server.dbname:xdjob}
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  main:
    show_banner: false

XD_ANALYTICS: ${analytics:redis}
XD_TRANSPORT: ${transport:redis}
XD_STORE: ${store:redis}
XD_HOME: ${xdHomeDir:..}

xd:
  data:
    home: file:${XD_HOME}/data
  config:
    home: file:${XD_HOME}/config
  module:
    home: file:${XD_HOME}/modules
  ui:
    home: file:${XD_HOME}/spring-xd-ui

server:
  port: ${PORT:9393}

---

spring:
  profiles: memory
transport: local
analytics: memory
store: memory
server:
  port: -1
management:
  port: -1

---

spring:
  profiles: rabbit
transport: rabbit

---

spring:
  profiles: cloud

xdHomeDir: .

---

spring:
  profiles: adminServer

---

spring:
  profiles: node
  batch:
    initializer:
      enabled: false
management:
  port: ${PORT:0}
server:
  port: ${PORT:0}

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: single
transport: local
store: memory
analytics: memory

