spring:
  profiles:
    active: default,hsqldb
  datasource:
    url: jdbc:hsqldb:hsql://localhost:9101/xdjob
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver

XD_ANALYTICS: ${analytics:redis}
XD_TRANSPORT: ${transport:redis}
XD_STORE: ${store:redis}
XD_HOME: ${xdHomeDir:..}

server:
  port: ${PORT:9393}

---

spring:
  profiles: memory
XD_TRANSPORT: local
XD_ANALYTICS: memory
XD_STORE: memory
server:
  port: 0
management:
  port: 0

---

spring:
  profiles: rabbit
XD_TRANSPORT: rabbit

---

spring:
  profiles: cloud

XD_HOME: .

---

spring:
  profiles: adminServer

---

spring:
  profiles: node
management:
  port: ${PORT:9000}
server:
  port: ${PORT:9000}

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: single
  datasource:
    url: jdbc:hsqldb:mem:xdjob
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver
transport: local
store: memory
analytics: memory

